spring.application.name=website

# Tell H2 to save data to a physical folder named 'data' inside your project
#spring.datasource.url=jdbc:h2:file:./data/vairotechdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Keep the H2 console enabled so you can look at the tables
#spring.h2.console.enabled=true

# Tell Hibernate to update the tables automatically without deleting them
#spring.jpa.hibernate.ddl-auto=update

# I am leaving in the H2 database configurations to use for later offline local testing

#The Supabase PostgreSQL Configs

spring.datasource.url=jdbc:postgresql://ep-steep-voice-avkes4ph.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jNexd3wuQS0W
spring.datasource.driver-class-name=org.postgresql.Driver

# The Hibernate Settings (TO autocreate the tables)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true