spring.application.name=website

# Tell H2 to save data to a physical folder named 'data' inside your project
spring.datasource.url=jdbc:h2:file:./data/vairotechdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Keep the H2 console enabled so you can look at the tables
spring.h2.console.enabled=true

# Tell Hibernate to update the tables automatically without deleting them
spring.jpa.hibernate.ddl-auto=update
